use_frameworks!

target 'LJMenu_Example' do
  pod 'LJMenu', :path => '../'

  target 'LJMenu_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
